/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AB/meta/AB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AC/meta/AC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ACO/meta/ACO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AFB/meta/AFB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AGH/meta/AGH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AGS/meta/AGS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AI/meta/AI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AL/meta/AL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AN/meta/AN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ANG/meta/ANG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ANT/meta/ANT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ANW/meta/ANW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AR/meta/AR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ARC/meta/ARC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AS/meta/AS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ASH/meta/ASH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ASL/meta/ASL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ASQ/meta/ASQ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AST/meta/AST_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ATE/meta/ATE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ATH/meta/ATH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ATS/meta/ATS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AW/meta/AW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/AX/meta/AX_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BA/meta/BA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BAB/meta/BAB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BAS/meta/BAS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BBM/meta/BBM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BBR/meta/BBR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BC/meta/BC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BCC/meta/BCC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BCF/meta/BCF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BCR/meta/BCR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BD/meta/BD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BEA/meta/BEA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BEG/meta/BEG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BF/meta/BF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BFD/meta/BFD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BGR/meta/BGR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BHP/meta/BHP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BI/meta/BI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BL/meta/BL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BLB/meta/BLB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BLC/meta/BLC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BLF/meta/BLF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BM/meta/BM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BMO/meta/BMO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BNS/meta/BNS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BOA/meta/BOA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BRL/meta/BRL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BRS/meta/BRS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BSB/meta/BSB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BSC/meta/BSC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BSG/meta/BSG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BSH/meta/BSH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BSN/meta/BSN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BSP/meta/BSP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BST/meta/BST_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BTF/meta/BTF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BTR/meta/BTR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BTS/meta/BTS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BU/meta/BU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BUD/meta/BUD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BW/meta/BW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BWL/meta/BWL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BYM/meta/BYM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/BYR/meta/BYR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CA/meta/CA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CAC/meta/CAC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CAM/meta/CAM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CAT/meta/CAT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CBU/meta/CBU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CCL/meta/CCL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CCS/meta/CCS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CD/meta/CD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CDH/meta/CDH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CFL/meta/CFL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CH/meta/CH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHA/meta/CHA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHC/meta/CHC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHD/meta/CHD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHI/meta/CHI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHM/meta/CHM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHS/meta/CHS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CHU/meta/CHU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CK/meta/CK_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CM/meta/CM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CNR/meta/CNR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CO/meta/CO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/COB/meta/COB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/COE/meta/COE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/COK/meta/COK_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/COL/meta/COL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/COT/meta/COT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/COY/meta/COY_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CP/meta/CP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CRF/meta/CRF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CRH/meta/CRH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CRS/meta/CRS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CS/meta/CS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CSH/meta/CSH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CST/meta/CST_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CT/meta/CT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CTH/meta/CTH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CTT/meta/CTT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/CW/meta/CW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DAS/meta/DAS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DE/meta/DE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DEH/meta/DEH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DG/meta/DG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DHU/meta/DHU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DO/meta/DO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DOG/meta/DOG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DP/meta/DP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DR/meta/DR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DS/meta/DS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/DSH/meta/DSH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EB/meta/EB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EEO/meta/EEO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EGF/meta/EGF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EGW/meta/EGW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EH/meta/EH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EHA/meta/EHA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ELB/meta/ELB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EM/meta/EM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EO/meta/EO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EPC/meta/EPC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EPO/meta/EPO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EPT/meta/EPT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ES/meta/ES_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ESH/meta/ESH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ESQ/meta/ESQ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EUR/meta/EUR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EUS/meta/EUS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EV/meta/EV_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/EYV/meta/EYV_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FBI/meta/FBI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FDO/meta/FDO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FF/meta/FF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FG/meta/FG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FL/meta/FL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FLA/meta/FLA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FLF/meta/FLF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FOX/meta/FOX_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FPF/meta/FPF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FRG/meta/FRG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/FS/meta/FS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GA/meta/GA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GAC/meta/GAC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GB/meta/GB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GCO/meta/GCO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GD/meta/GD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GE/meta/GE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GF/meta/GF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GHL/meta/GHL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GI/meta/GI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GJ/meta/GJ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GP/meta/GP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GSQ/meta/GSQ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GST/meta/GST_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GT/meta/GT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GTW/meta/GTW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GU/meta/GU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/GUP/meta/GUP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HA/meta/HA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HAG/meta/HAG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HAM/meta/HAM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HAQ/meta/HAQ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HE/meta/HE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HFP/meta/HFP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HH/meta/HH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HOO/meta/HOO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HP/meta/HP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HS/meta/HS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HT/meta/HT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/HU/meta/HU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/IE/meta/IE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/IP/meta/IP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JA/meta/JA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JAK/meta/JAK_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JCH/meta/JCH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JL/meta/JL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JMD/meta/JMD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JS/meta/JS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/JSS/meta/JSS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KBT/meta/KBT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KCO/meta/KCO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KIS/meta/KIS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KO/meta/KO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KOA/meta/KOA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KP/meta/KP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/KT/meta/KT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LB/meta/LB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LEC/meta/LEC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LIL/meta/LIL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LO/meta/LO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LOB/meta/LOB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LOW/meta/LOW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LPW/meta/LPW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LSH/meta/LSH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LUF/meta/LUF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/LYN/meta/LYN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MA/meta/MA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MAA/meta/MAA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MAG/meta/MAG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MAI/meta/MAI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MAR/meta/MAR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MAS/meta/MAS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MAT/meta/MAT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MB/meta/MB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MBI/meta/MBI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MCB/meta/MCB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MCL/meta/MCL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MEE/meta/MEE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MF/meta/MF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MH/meta/MH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MOL/meta/MOL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MOS/meta/MOS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MS/meta/MS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MSB/meta/MSB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MST/meta/MST_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MT/meta/MT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MU/meta/MU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MUS/meta/MUS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/MUT/meta/MUT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NAP/meta/NAP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NAS/meta/NAS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NBI/meta/NBI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NCL/meta/NCL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NE/meta/NE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NH/meta/NH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NIL/meta/NIL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NIP/meta/NIP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NM/meta/NM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NMO/meta/NMO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NPI/meta/NPI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/NY/meta/NY_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/OCP/meta/OCP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/OG/meta/OG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/OHH/meta/OHH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/OU/meta/OU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/OWL/meta/OWL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/OWP/meta/OWP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PA/meta/PA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PAG/meta/PAG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PAO/meta/PAO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PBP/meta/PBP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PC/meta/PC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PCA/meta/PCA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PCO/meta/PCO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PD/meta/PD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PDO/meta/PDO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PEC/meta/PEC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PF/meta/PF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PGR/meta/PGR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PI/meta/PI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PIG/meta/PIG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PLF/meta/PLF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PLJ/meta/PLJ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PO/meta/PO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/POL/meta/POL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PP/meta/PP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PR/meta/PR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PRA/meta/PRA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PRF/meta/PRF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PS/meta/PS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PSU/meta/PSU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PT/meta/PT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PTO/meta/PTO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/PW/meta/PW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RA/meta/RA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RAB/meta/RAB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RAD/meta/RAD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RAT/meta/RAT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RAY/meta/RAY_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RD/meta/RD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RED/meta/RED_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RET/meta/RET_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RH/meta/RH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RHI/meta/RHI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RI/meta/RI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RIN/meta/RIN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RKI/meta/RKI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RL/meta/RL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RLF/meta/RLF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RNP/meta/RNP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ROA/meta/ROA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ROD/meta/ROD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ROF/meta/ROF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RP/meta/RP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RRH/meta/RRH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RS/meta/RS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RSQ/meta/RSQ_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RT/meta/RT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RUL/meta/RUL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/RYB/meta/RYB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SAA/meta/SAA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SAB/meta/SAB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SAD/meta/SAD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SAF/meta/SAF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SBE/meta/SBE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SBT/meta/SBT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SCU/meta/SCU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SDF/meta/SDF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SE/meta/SE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SEM/meta/SEM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SER/meta/SER_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SF/meta/SF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SG/meta/SG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SGO/meta/SGO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SI/meta/SI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SID/meta/SID_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SIL/meta/SIL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SIS/meta/SIS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SIT/meta/SIT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SKI/meta/SKI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SL/meta/SL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SLT/meta/SLT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SM/meta/SM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SME/meta/SME_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SMO/meta/SMO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SNB/meta/SNB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SOS/meta/SOS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SPB/meta/SPB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SPM/meta/SPM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SQM/meta/SQM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SR/meta/SR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SRB/meta/SRB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SSC/meta/SSC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SSL/meta/SSL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SSN/meta/SSN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SSR/meta/SSR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ST/meta/ST_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/STB/meta/STB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/STL/meta/STL_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/STO/meta/STO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/STR/meta/STR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/STS/meta/STS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SV/meta/SV_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SWC/meta/SWC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/SWF/meta/SWF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TAM/meta/TAM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TAO/meta/TAO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TBF/meta/TBF_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TEN/meta/TEN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TH/meta/TH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TIB/meta/TIB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TM/meta/TM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TMB/meta/TMB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TRS/meta/TRS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TS/meta/TS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TUP/meta/TUP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TUR/meta/TUR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TUT/meta/TUT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/TW/meta/TW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/UO/meta/UO_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/UR/meta/UR_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/VC/meta/VC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/VG/meta/VG_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/VI/meta/VI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/VIS/meta/VIS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/VW/meta/VW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WB/meta/WB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WBU/meta/WBU_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WBW/meta/WBW_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WC/meta/WC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WCA/meta/WCA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WE/meta/WE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WEA/meta/WEA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WEC/meta/WEC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WFA/meta/WFA_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WFB/meta/WFB_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WFS/meta/WFS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WHE/meta/WHE_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WHH/meta/WHH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WHS/meta/WHS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WI/meta/WI_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WIS/meta/WIS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WM/meta/WM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WMH/meta/WMH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WRS/meta/WRS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WS/meta/WS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/WSD/meta/WSD_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/XEN/meta/XEN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YAN/meta/YAN_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YBH/meta/YBH_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YC/meta/YC_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YFS/meta/YFS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YFT/meta/YFT_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YNM/meta/YNM_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YS/meta/YS_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/YSP/meta/YSP_RefFreeDMA.cfg
/home/lv71484/droman/reffreedma/RefFreeDMA/scripts/cleanup.sh /global/lv71484/droman/DNAmeth500species//results_pipeline/ZE/meta/ZE_RefFreeDMA.cfg
